# Generated by Django 4.0 on 2021-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FartilizerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=200)),
                ('f_price', models.FloatField()),
                ('f_digital', models.BooleanField(blank=True, default=False, null=True)),
                ('f_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
