# Generated by Django 4.0 on 2021-12-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_fartilizerproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fartilizerproduct',
            old_name='f_digital',
            new_name='digital',
        ),
        migrations.RenameField(
            model_name='fartilizerproduct',
            old_name='f_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='fartilizerproduct',
            old_name='F_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fartilizerproduct',
            old_name='f_price',
            new_name='price',
        ),
    ]
