# Generated by Django 4.0 on 2021-12-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_instractions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='instractions',
            new_name='AgriInstraction',
        ),
    ]
