# Generated by Django 4.0 on 2021-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_agrisolution_alter_agriinstraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrisolution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
