# Generated by Django 4.0 on 2021-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_remove_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fartilizerproduct',
            name='image',
            field=models.ImageField(upload_to='farmer/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='farmer/images'),
        ),
    ]
