# Generated by Django 4.0 on 2021-12-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
